name: Gendiff test and lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: linter
        run: make lint
      - name: test
        run: make test
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 268149fdc01b007176e8039f4ddfa1fa24d6596ddc2d759bde00b525a5f2c1d6
        with:
         coverageCommand: make coverage
