name: Gendiff test and lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: linter
        run: make lint
      - name: test
        run: make test
