name: Gendiff test and lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: linter
        run: make lint
      - name: test
        run: make test
      - name: publish code coverage to code-climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: a92996b30a5fdbe55f78259d05b1f23a5fb80be5fa68ab992d782d0fe4c3e622
        with:
          run: make coverage
